<?php
/**
 * Created by PhpStorm.
 * User: lenovo
 * Date: 6/15/2018
 * Time: 9:33 AM
 */
namespace TimSDK\Container;

use Pimple\Container;
use Pimple\Exception\UnknownIdentifierException;

class ServiceContainer extends Container
{
    /**
     * @var static
     */
    protected static $instance;

    /**
     * @var array
     */
    protected $instances;

    /**
     * Magic get access.
     *
     * @param string $id
     * @return mixed|null
     * @throws UnknownIdentifierException
     */
    public function __get($id)
    {
        return $this->offsetGet($id);
    }

    /**
     * Magic set access.
     *
     * @param string $id
     * @param mixed  $value
     */
    public function __set($id, $value)
    {
        $this->offsetSet($id, $value);
    }

    /**
     * @param ServiceContainer $instance
     * @return ServiceContainer
     */
    public static function setInstance(ServiceContainer $instance = null)
    {
        return self::$instance = $instance;
    }

    /**
     * Set the globally available instance of the container.
     *
     * @return static
     */
    public static function getInstance()
    {
        if (is_null(static::$instance)) {
            static::$instance = new static;
        }
        return static::$instance;
    }

    /**
     * Register an existing instance as shared in the container.
     *
     * @param $abstract
     * @param $instance
     * @return mixed
     */
    public function instance($abstract, $instance)
    {
        $this->instances[$abstract] = $instance;

        return $instance;
    }

    /**
     * Gets a parameter or an object.
     *
     * @param string $id The unique identifier for the parameter or object
     *
     * @return mixed The value of the parameter or an object
     *
     * @throws UnknownIdentifierException If the identifier is not defined
     */
    public function offsetGet($id)
    {
        if (isset($this->instances[$id])) {
            return $this->instances[$id];
        }

        return parent::offsetGet($id); // TODO: Change the autogenerated stub
    }
}
