tools:
    external_code_coverage: true
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
checks:
    php: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    nodes:
        php55:
            environment:
                php: 5.5
        php56:
            environment:
                php: 5.6
        php70:
            environment:
                php: 7.0
    dependencies:
            before:
                - composer self-update
                - composer install --prefer-source --no-interaction --dev
                - ./vendor/bin/phplint
    tests:
        override:
            -
                command: ./vendor/bin/phpunit --coverage-clover=./build/logs/clover.xml
                coverage:
                    file: ./build/logs/clover.xml
                    format: clover
