language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - ./vendor/bin/phplint

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml

script: ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
